<?php
    //Common
    define('GET_SUCCESS', 'GET_SUCCESS');
    define('ID_NOT_FOUND', 'ID_NOT_FOUND');

    // Login
    define('LOGIN_SUCCESS', 'LOGIN_SUCCESS');
    define('LOGIN_FAIL', 'LOGIN_FAIL');
    define('EMPTY_USERNAME', 'EMPTY_USERNAME');
    define('EMPTY_PASSWORD', 'EMPTY_PASSWORD');

    // Member
    define('EMPTY_FULLNAME', 'EMPTY_FULLNAME');
    define('EMPTY_IS_MALE', 'EMPTY_IS_MALE');
    define('EMPTY_BIRTHDAY', 'EMPTY_BIRTHDAY');
    define('EMPTY_EMAIL', 'EMPTY_EMAIL');
    define('EMPTY_PHONE', 'EMPTY_PHONE');
    define('EMPTY_ACCESS_LEVEL', 'EMPTY_ACCESS_LEVEL');
    define('EMPTY_EXECUTE_BY', 'EMPTY_EXECUTE_BY');
    define('IDENTICAL_USERNAME', 'IDENTICAL_USERNAME');
    define('FORMAT_INVALID_IS_MALE', 'FORMAT_INVALID_IS_MALE');
    define('FORMAT_INVALID_BIRTHDAY', 'FORMAT_INVALID_BIRTHDAY');
    define('FORMAT_INVALID_EMAIL', 'FORMAT_INVALID_EMAIL');
    define('FORMAT_INVALID_PHONE', 'FORMAT_INVALID_PHONE');
    define('FORMAT_INVALID_IMAGE', 'FORMAT_INVALID_IMAGE');
    define('MAX_SIZE_PICTURE', 'MAX_SIZE_PICTURE');
    define('INTEGER_ACCESS_LEVEL', 'INTEGER_ACCESS_LEVEL');
    define('INTEGER_EXECUTE_BY', 'INTEGER_EXECUTE_BY');

    // Config
    define('GET_CONFIG_SUCCESS', 'GET_CONFIG_SUCCESS');
    define('GET_CONFIG_FAIL', 'GET_CONFIG_FAIL');

    // Team
    define('GET_ALL_TEAM_SUCCESS', 'GET_ALL_TEAM_SUCCESS');
    define('TEAM_NOT_FOUND', 'TEAM_NOT_FOUND');
    define('GET_MEMBERS_OF_TEAM_SUCCESS', 'GET_MEMBERS_OF_TEAM_SUCCESS');
    define('GET_MEMBERS_OF_TEAM_FAIL', 'GET_MEMBERS_OF_TEAM_FAIL');


    